apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: assignment01-deploy
        image: vrajmonash/flask_app:least
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits: 
            memory: 512Mi
            cpu: 500m
        ports:
        - containerPort: 5050
          
---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:  
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      nodePort: 31000
      targetPort: 5050
      port: 5050
      
